apiVersion: v1
kind: Pod
metadata:
  name: backend-deployment
spec:
  containers:
    - name: soa-backend
      image: soa_backend:latest
      imagePullPolicy : Never
      resources:
        limits:
          memory: "200Mi"
