apiVersion: v1
kind: Pod
metadata:
  name: food-deployment
spec:
  containers:
    - name: soa-food
      image: soa_food:latest
      imagePullPolicy : Never
      resources:
        limits:
          memory: "200Mi"
