apiVersion: v1
kind: Pod
metadata:
  name: web-app-deployment
spec:
  containers:
    - name: web-app
      image: web-app:latest
      imagePullPolicy : Never
      resources:
        limits:
          memory: "200Mi"
