apiVersion: v1
kind: Pod
metadata:
  name: time-deployment
spec:
  containers:
    - name: soa-time
      image: soa_time:latest
      imagePullPolicy : Never
      resources:
        limits:
          memory: "200Mi"
